import { NextPage } from "next";
import styled from "@emotion/styled";
import Head from "next/head";

import { DetailHeader } from "../../../components/Details/DetailHeader";
import { LeftHeader } from "../../../components/Details/LeftHeader";
import { RightHeader } from "../../../components/Details/RightHeader";

// import { CardContainer } from "../../../components/Home/CardContainer";
import { Header } from "../../../components/Common/Header";

import { Theme } from "../../../styles/theme";
import { useContext, useEffect, useState } from "react";
import { ThemeContext } from "../../_app";
import { useRouter } from "next/router";
import { useData } from "../../../hooks/useData";
import { ErrorPage } from "../../../components/Details/ErrorPage";

interface ThemeProps {
  theme: Theme;
}

interface User {
  id: number;
  username: string;
  email: string;
  provider: string;
  confirmed: boolean;
  blocked: boolean;
  createdAt: string;
  updatedAt: string;
}

interface Post {
  id: number;
  attributes: {
    userid: Data;
    title: string;
    contents: string;
    published: boolean;
    createdAt: string;
    updatedAt: string;
    publishedAt: string;
    url: string;
    private: null;
  };
}

interface Data {
  data: UserAtt;
}

interface UserAtt {
  attributes: UserNick;
}

interface UserNick {
  nickname: string;
}

const DetailsIndexPage: NextPage = () => {
  const { theme } = useContext(ThemeContext);
  const router = useRouter();
  const userName = router.query.id;
  const userDetails = router.query.details;
  let postObj = {
    title: "",
    contents: "",
    url: "",
  };

  const { data: DetailData, error } = useData("posts?populate=*");

  if (!DetailData) return <div>로딩중</div>;
  if (error) return <div>에러</div>;

  DetailData.data.some((details: Post) => {
    if (
      userDetails === details.attributes.url &&
      userName === details.attributes.userid.data.attributes.nickname
    ) {
      postObj = details.attributes;
      console.log(postObj);
      return true;
    }
  });

  return (
    <main>
      <Head>
        <title>Space Dev Club</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {postObj.title ? (
        <div>
          <Header username={"deli-ght"} user={true} />
          <DetailContainer>
            <LeftHeader />
            <DetailHeader
              title={postObj.title}
              contents={postObj.contents}
              userName={userName}
            />
            <RightHeader />
          </DetailContainer>
          <PostsContainer theme={theme}>
            {/* <CardContainer filter="zz" /> */}
          </PostsContainer>
        </div>
      ) : (
        <ErrorPage />
      )}
    </main>
  );
};

export default DetailsIndexPage;

const DetailContainer = styled.section`
  position: relative;
  display: flex;
  width: 100%;
  justify-content: center;
`;

const PostsContainer = styled.div<ThemeProps>`
  width: 100%;
  display: flex;
  justify-content: center;
  background-color: ${({ theme }) => theme.BACKGROUND};
  box-shadow: rgb(0 0 0 / 8%) 0px 0px 32px;
  margin-top: 50px;
`;
