import styled from "@emotion/styled"
import Head from "next/head"
import qs from "qs"
import React, { ReactNode } from "react"
import { useData } from "../../hooks/useData"
import { Header } from "../Common/Header"
import { ErrorPage } from "../Common/ErrorPage"
import { Intro } from "./"
import { Mymenu } from "./Mymenu"
import CardLoading from "../Common/CardLoading"

interface LayoutProps {
  username: string | string[] | undefined
  user: boolean
  indexnum: number
  children?: ReactNode
}

const MypageLayout: React.FC<LayoutProps> = ({
  username,
  user,
  indexnum,
  children,
}) => {
  const query = qs.stringify(
    {
      filters: {
        userid: {
          $eq: username,
        },
      },
    },
    {
      encodeValuesOnly: true,
    }
  )

  const { data, error, isValidating } = useData("userinfos", query)

  if (isValidating) return <CardLoading />
  if (!data?.data[0]) return <ErrorPage />
  return (
    <>
      <Head>
        <title>{username} velog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/image/스데브.png" />
      </Head>
      <section>
        <Header
          username={username}
          user={user}
          velogtitle={data.data[0].attributes.velogtitle}
        />
        <Main>
          <Intro username={username} userdata={data.data[0].attributes} />
          <Mymenu username={username} indexnum={indexnum} />
          {children}
        </Main>
      </section>
    </>
  )
}

const Main = styled.main`
  width: 768px;
  margin: 0 auto;

  @media screen and (max-width: 768px) {
    width: 100%;
  }
`

export default MypageLayout
