import styled from "@emotion/styled"
import Head from "next/head"
import React, { ReactNode } from "react"
import { Header } from "../Common/Header"
import { Intro } from "./"
import { Mymenu } from "./Mymenu"

interface LayoutProps {
  username: string | string[] | undefined
  user: boolean
  indexnum: number
  children?: ReactNode
}

const MypageLayout: React.FC<LayoutProps> = ({
  username,
  user,
  indexnum,
  children,
}) => {
  return (
    <>
      <Head>
        <title>Space Dev Club</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <Header username={username} user={user} />
        <Main>
          <Intro />
          <Mymenu username={username} indexnum={indexnum} />
          {children}
        </Main>
      </section>
    </>
  )
}

const Main = styled.main`
  width: 768px;
  margin: 0 auto;

  @media screen and (max-width: 768px) {
    width: 100%;
  }
`

export default MypageLayout
