import type { NextPage } from "next"
import Head from "next/head"
import { Mypage } from "./mypage"

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <h1>Space Dev Club</h1> */}
        <Mypage />
      </main>
    </>
  )
}

export default Home
