import styled from "@emotion/styled"
import { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import React from "react"
import { Header, Intro, Mymenu } from "../../components/MyPage"

const Mypage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Space Dev Club</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <Header username={"deli-ght"} user={true} />
        <Main>
          <Intro />
          <Mymenu />
        </Main>
      </body>
    </>
  )
}

const Main = styled.main`
  width: 768px;
  margin: 0 auto;

  @media screen and (max-width: 768px) {
    width: 100%;
  }
`

export default Mypage
