import { NextPage } from "next";
import styled from "@emotion/styled";
import Head from "next/head";
import Image from "next/image";
import { DetailHeader } from "../../components/Details/DetailHeader";
import { LeftHeader } from "../../components/Details/LeftHeader";
import { RightHeader } from "../../components/Details/RightHeader";
import { Header } from "../../components/MyPage";

const DetailsIndexPage: NextPage = () => {
  return (
    <main>
      <Head>
        <title>Space Dev Club</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header username={"deli-ght"} user={true} />
      <DetailContainer>
        <LeftHeader />
        <DetailHeader />
        <RightHeader />
      </DetailContainer>
    </main>
  );
};

export default DetailsIndexPage;

const DetailContainer = styled.section`
  display: flex;
  width: 100%;
  justify-content: center;
`;
